const crypto = require('crypto');

const SITE_COMPILER_VERSION = 'piki-site-1';
const MAX_HTML_LENGTH = 120_000;
const MAX_CSS_LENGTH = 80_000;
const REQUIRED_SLOT = 'piki-products';
const SINGLE_PRODUCT_SLOT = 'piki-single-product';
const REQUIRED_PAGE_SLOT = 'piki-page-content';
const SUPPORTED_SLOTS = Object.freeze([
  'piki-brand',
  'piki-store-intro',
  'piki-cover',
  'piki-navigation',
  'piki-categories',
  'piki-search',
  'piki-products',
  'piki-single-product',
  'piki-cart-button',
  'piki-whatsapp',
  'piki-page-content',
  'piki-footer',
]);

const BLOCKED_HTML_PATTERNS = Object.freeze([
  { pattern: /<\s*\/?\s*script\b/i, message: 'Generated scripts are not allowed.' },
  { pattern: /<\s*\/?\s*iframe\b/i, message: 'Generated iframes are not allowed.' },
  { pattern: /<\s*\/?\s*(?:object|embed|applet|portal)\b/i, message: 'Embedded executable content is not allowed.' },
  { pattern: /<\s*\/?\s*(?:form|input|textarea|select|option)\b/i, message: 'Generated forms are not allowed. Use Piki checkout bindings.' },
  { pattern: /<\s*\/?\s*(?:meta|base|link|style|html|head|body)\b/i, message: 'Document-level tags are managed by the Piki compiler.' },
  { pattern: /<\s*\/?\s*(?:svg|math)\b/i, message: 'Inline SVG and MathML are not accepted in generated source.' },
  { pattern: /<\s*\/?\s*(?:img|video|audio|source)\b/i, message: 'Generated media URLs are not allowed. Use Piki brand and product bindings.' },
  { pattern: /\s(?:on[a-z]+|srcdoc|style)\s*=/i, message: 'Event handlers, inline styles, and nested documents are not allowed.' },
  { pattern: /\s(?:src|srcset|poster|background|action|formaction|ping|data)\s*=/i, message: 'Generated URL-bearing attributes are not allowed. Use trusted Piki media and action bindings.' },
  { pattern: /(?:javascript|vbscript)\s*:/i, message: 'Executable URLs are not allowed.' },
  { pattern: /data\s*:\s*text\/html/i, message: 'HTML data URLs are not allowed.' },
]);

const BLOCKED_CSS_PATTERNS = Object.freeze([
  { pattern: /<\s*\/\s*style/i, message: 'CSS cannot close the compiler style boundary.' },
  { pattern: /@import\b/i, message: 'External CSS imports are not allowed.' },
  { pattern: /expression\s*\(/i, message: 'Executable CSS expressions are not allowed.' },
  { pattern: /(?:javascript|vbscript)\s*:/i, message: 'Executable CSS URLs are not allowed.' },
  { pattern: /behavior\s*:/i, message: 'Executable CSS behavior is not allowed.' },
  { pattern: /-moz-binding\s*:/i, message: 'Browser bindings are not allowed.' },
  { pattern: /url\s*\(/i, message: 'Generated CSS assets are not allowed. Product and brand images use trusted Piki bindings.' },
  { pattern: /(?:image|(?:-webkit-)?image-set)\s*\(/i, message: 'Generated CSS image sources are not allowed. Use trusted Piki media bindings.' },
]);

function compileStorefrontSitePackage(input = {}) {
  const raw = objectValue(input);
  const name = limitText(raw.name, 100) || 'Piki generated storefront';
  const summary = limitText(raw.summary, 300) || 'A custom storefront generated by Piki.';
  const html = normalizeSource(raw.html ?? raw.markup, MAX_HTML_LENGTH, 'HTML');
  const pageHtml = normalizeSource(
    raw.pageHtml ?? raw.pageMarkup ?? defaultPageShell(),
    MAX_HTML_LENGTH,
    'Page HTML',
  );
  const css = normalizeSource(raw.css ?? raw.styles, MAX_CSS_LENGTH, 'CSS');

  if (!html) throw createError(400, 'Generated site HTML is required.');
  if (!css) throw createError(400, 'Generated site CSS is required.');
  validatePatterns(html, BLOCKED_HTML_PATTERNS);
  validatePatterns(pageHtml, BLOCKED_HTML_PATTERNS);
  validatePatterns(css, BLOCKED_CSS_PATTERNS);
  validateSafeLinks(html);
  validateSafeLinks(pageHtml);

  const slotCounts = countSlots(html);
  validateBindingMarkup(html, slotCounts);
  const slots = SUPPORTED_SLOTS.filter((slot) => slotCounts[slot] > 0);
  const productBindingCount =
    slotCounts[REQUIRED_SLOT] + slotCounts[SINGLE_PRODUCT_SLOT];
  if (productBindingCount !== 1) {
    throw createError(
      400,
      'Generated storefront must include exactly one product binding: <piki-products></piki-products> or <piki-single-product></piki-single-product>.',
    );
  }
  const singleProductId = slotCounts[SINGLE_PRODUCT_SLOT]
    ? limitText(raw.singleProductId, 180) ||
      readBindingAttribute(html, SINGLE_PRODUCT_SLOT, 'product-id')
    : null;
  if (slotCounts[SINGLE_PRODUCT_SLOT] && !singleProductId) {
    throw createError(
      400,
      'The <piki-single-product> binding requires a selected live product ID.',
    );
  }
  if (
    singleProductId &&
    !/^[^\u0000-\u001f]{1,180}$/.test(singleProductId)
  ) {
    throw createError(400, 'The single-product binding contains an invalid product ID.');
  }
  const pageSlotCounts = countSlots(pageHtml);
  validateBindingMarkup(pageHtml, pageSlotCounts);
  const pageSlots = SUPPORTED_SLOTS.filter((slot) => pageSlotCounts[slot] > 0);
  if (pageSlotCounts[REQUIRED_PAGE_SLOT] !== 1) {
    throw createError(
      400,
      'Generated page shell must include exactly one <piki-page-content></piki-page-content> binding.',
    );
  }
  const unknownSlots = [
    ...`${html}\n${pageHtml}`.matchAll(/<\s*(piki-[a-z0-9-]+)\b/gi),
  ]
    .map((match) => match[1].toLowerCase())
    .filter((slot) => !SUPPORTED_SLOTS.includes(slot));
  if (unknownSlots.length) {
    throw createError(
      400,
      `Unsupported Piki binding: ${[...new Set(unknownSlots)].join(', ')}.`,
    );
  }

  const source = {
    name,
    summary,
    html,
    pageHtml,
    css,
    ...(singleProductId ? { singleProductId } : {}),
  };
  const codeHash = crypto
    .createHash('sha256')
    .update(JSON.stringify(source))
    .digest('hex');
  return {
    ...source,
    compilerVersion: SITE_COMPILER_VERSION,
    codeHash,
    slots,
    pageSlots,
    singleProductId,
    security: {
      passed: true,
      scriptPolicy: 'platform-only',
      sandbox: 'opaque-origin',
      networkAccess: 'platform-assets-only',
    },
  };
}

function defaultStorefrontSitePackage({
  businessName = 'Your store',
  singleProductId = null,
} = {}) {
  if (singleProductId) {
    return compileStorefrontSitePackage({
      name: `${businessName} product storefront`,
      summary:
        'A resilient one-product storefront with a focused live purchase journey.',
      singleProductId,
      html: `
<div class="site-shell product-site">
  <header class="site-header">
    <piki-brand></piki-brand>
    <piki-navigation></piki-navigation>
    <piki-cart-button></piki-cart-button>
  </header>
  <main>
    <section class="product-hero">
      <piki-single-product></piki-single-product>
    </section>
    <section class="product-support">
      <p>Questions before ordering?</p>
      <piki-whatsapp></piki-whatsapp>
    </section>
  </main>
  <piki-footer></piki-footer>
</div>`,
      pageHtml: defaultPageShell(),
      css: `
:root { color-scheme: light; --ink: #161616; --paper: #fbfaf7; --accent: #d14343; --line: rgba(22,22,22,.12); }
* { box-sizing: border-box; }
body { margin: 0; background: var(--paper); color: var(--ink); font-family: Inter, ui-sans-serif, system-ui, sans-serif; }
.site-shell { min-height: 100vh; }
.site-header { position: sticky; top: 0; z-index: 20; display: grid; grid-template-columns: 1fr auto auto; align-items: center; gap: 24px; padding: 18px clamp(20px,5vw,72px); border-bottom: 1px solid var(--line); background: rgba(251,250,247,.94); backdrop-filter: blur(18px); }
.product-hero { padding: clamp(36px,7vw,100px) clamp(20px,7vw,110px); }
.product-support { display:flex; align-items:center; justify-content:center; gap:18px; flex-wrap:wrap; padding:34px 20px; border-top:1px solid var(--line); border-bottom:1px solid var(--line); background:#f1eee8; }
.product-support p { margin:0; font-weight:800; }
@media (max-width: 760px) { .site-header { grid-template-columns: 1fr auto; } .site-header piki-navigation { display: none; } .product-hero { padding-inline: 14px; } }
`,
    });
  }
  return compileStorefrontSitePackage({
    name: `${businessName} custom storefront`,
    summary: 'A responsive, image-first storefront with category navigation.',
    html: `
<div class="site-shell">
  <header class="site-header">
    <piki-brand></piki-brand>
    <piki-navigation></piki-navigation>
    <piki-cart-button></piki-cart-button>
  </header>
  <main>
    <section class="hero">
      <piki-cover></piki-cover>
      <piki-store-intro></piki-store-intro>
    </section>
    <section class="shop-layout">
      <aside class="category-sidebar">
        <h2>Categories</h2>
        <piki-categories></piki-categories>
      </aside>
      <div class="catalog-content">
        <piki-search></piki-search>
        <piki-products></piki-products>
      </div>
    </section>
  </main>
  <piki-footer></piki-footer>
</div>`,
    pageHtml: defaultPageShell(),
    css: `
:root { color-scheme: light; --ink: #161616; --paper: #fbfaf7; --accent: #d14343; --line: rgba(22,22,22,.12); }
* { box-sizing: border-box; }
body { margin: 0; background: var(--paper); color: var(--ink); font-family: Inter, ui-sans-serif, system-ui, sans-serif; }
.site-shell { min-height: 100vh; }
.site-header { position: sticky; top: 0; z-index: 20; display: grid; grid-template-columns: 1fr auto auto; align-items: center; gap: 24px; padding: 18px clamp(20px,5vw,72px); border-bottom: 1px solid var(--line); background: rgba(251,250,247,.94); backdrop-filter: blur(18px); }
.hero { position:relative; overflow:hidden; padding: clamp(70px,10vw,150px) clamp(20px,8vw,120px); background: linear-gradient(135deg,#171717,#34201d); color: white; }
.hero::after { content:""; position:absolute; inset:0; background:linear-gradient(90deg,rgba(10,10,10,.92),rgba(10,10,10,.38)); }
.hero .piki-binding-cover { position:absolute; inset:0; width:100%; height:100%; object-fit:cover; opacity:.68; }
.hero .piki-binding-store-intro { position:relative; z-index:1; max-width:900px; }
.hero h1 { max-width: 900px; margin: 10px 0; font-size: clamp(48px,8vw,112px); line-height: .92; letter-spacing: -.055em; }
.hero p { max-width: 620px; font-size: clamp(16px,2vw,21px); line-height: 1.65; opacity: .78; }
.eyebrow { text-transform: uppercase; letter-spacing: .22em; font-size: 12px !important; font-weight: 800; }
.shop-layout { display: grid; grid-template-columns: minmax(210px,260px) minmax(0,1fr); gap: clamp(28px,5vw,72px); padding: clamp(40px,6vw,90px) clamp(20px,6vw,90px); }
.category-sidebar { position: sticky; top: 100px; align-self: start; }
.category-sidebar h2 { font-size: 13px; text-transform: uppercase; letter-spacing: .16em; }
@media (max-width: 760px) { .site-header { grid-template-columns: 1fr auto; } .site-header piki-navigation { display: none; } .shop-layout { grid-template-columns: 1fr; } .category-sidebar { position: static; } }
`,
  });
}

function defaultPageShell() {
  return `
<div class="site-shell piki-page-shell">
  <header class="site-header">
    <piki-brand></piki-brand>
    <piki-navigation></piki-navigation>
    <piki-cart-button></piki-cart-button>
  </header>
  <piki-page-content></piki-page-content>
  <piki-footer></piki-footer>
</div>`;
}

function countSlots(html) {
  return Object.fromEntries(
    SUPPORTED_SLOTS.map((slot) => [
      slot,
      [...html.matchAll(new RegExp(`<\\s*${slot}\\b`, 'gi'))].length,
    ]),
  );
}

function validateBindingMarkup(html, slotCounts) {
  for (const slot of SUPPORTED_SLOTS) {
    if (!slotCounts[slot]) continue;
    const paired = [
      ...html.matchAll(
        new RegExp(`<${slot}(?:\\s[^>]*)?>[\\s\\S]*?<\\/${slot}\\s*>`, 'gi'),
      ),
    ].length;
    const selfClosing = [
      ...html.matchAll(new RegExp(`<${slot}(?:\\s[^>]*)?\\s*\\/>`, 'gi')),
    ].length;
    if (paired + selfClosing !== slotCounts[slot]) {
      throw createError(
        400,
        `Generated Piki binding <${slot}> must be paired or self-closing.`,
      );
    }
  }
}

function validatePatterns(value, rules) {
  for (const rule of rules) {
    if (rule.pattern.test(value)) throw createError(400, rule.message);
  }
}

function validateSafeLinks(html) {
  for (const match of html.matchAll(/\shref\s*=\s*(["'])(.*?)\1/gi)) {
    if (!match[2].trim().startsWith('#')) {
      throw createError(
        400,
        'Generated links must be local page anchors. Use Piki navigation and WhatsApp bindings for other destinations.',
      );
    }
  }
  if (/\shref\s*=\s*[^\s"'][^\s>]*/i.test(html)) {
    throw createError(400, 'Generated links must use a quoted local page anchor.');
  }
}

function readBindingAttribute(html, slot, attribute) {
  const opening = html.match(new RegExp(`<\\s*${slot}\\b([^>]*)>`, 'i'));
  if (!opening) return null;
  const attributes = opening[1] || '';
  const match = attributes.match(
    new RegExp(`(?:^|\\s)${attribute}\\s*=\\s*(["'])(.*?)\\1`, 'i'),
  );
  return match?.[2]?.trim() || null;
}

function normalizeSource(value, maxLength, label) {
  const source = String(value ?? '').replace(/^\uFEFF/, '').trim();
  if (source.length > maxLength) {
    throw createError(413, `${label} exceeds the Piki compiler limit.`);
  }
  return source;
}

function objectValue(value) {
  return value && typeof value === 'object' && !Array.isArray(value) ? value : {};
}

function limitText(value, maxLength) {
  const clean = String(value ?? '').trim();
  return clean ? clean.slice(0, maxLength) : '';
}

function createError(statusCode, message) {
  const error = new Error(message);
  error.statusCode = statusCode;
  return error;
}

module.exports = {
  SITE_COMPILER_VERSION,
  SUPPORTED_SLOTS,
  compileStorefrontSitePackage,
  defaultStorefrontSitePackage,
};
