const syncTables = [
  {
    name: 'branches',
    columns: [
      'id',
      'name',
      'code',
      'phone',
      'address',
      'is_active',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'categories',
    columns: [
      'id',
      'branch_id',
      'name',
      'color',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'expense_categories',
    columns: [
      'id',
      'branch_id',
      'name',
      'color',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'users',
    columns: [
      'id',
      'name',
      'email',
      'phone',
      'password',
      'role',
      'feature_access_json',
      'allowed_service_ids_json',
      'allowed_branch_ids_json',
      'pos_mode',
      'service_order_scope',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'customers',
    columns: [
      'id',
      'branch_id',
      'name',
      'phone',
      'email',
      'balance',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'shifts',
    columns: [
      'id',
      'branch_id',
      'user_id',
      'cashier_name',
      'status',
      'opening_cash',
      'closing_cash_counted',
      'expected_cash',
      'cash_sales_total',
      'cash_refunds_total',
      'cash_in_total',
      'cash_out_total',
      'difference',
      'note',
      'opened_at',
      'closed_at',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'suppliers',
    columns: [
      'id',
      'branch_id',
      'name',
      'phone',
      'email',
      'address',
      'note',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'products',
    columns: [
      'id',
      'branch_id',
      'name',
      'price',
      'cost',
      'stock',
      'low_stock',
      'unit',
      'stock_unit',
      'sale_unit',
      'sale_to_stock_factor',
      'purchase_unit',
      'purchase_to_stock_factor',
      'sku',
      'barcode',
      'image_url',
      'brand',
      'description',
      'image_urls_json',
      'show_online',
      'is_featured',
      'category_id',
      'track_stock',
      'has_variants',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'product_variants',
    columns: [
      'id',
      'branch_id',
      'product_id',
      'name',
      'price',
      'cost',
      'sku',
      'barcode',
      'stock',
      'low_stock',
      'sort_order',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'product_variant_colors',
    columns: [
      'id',
      'branch_id',
      'product_id',
      'variant_id',
      'name',
      'hex_color',
      'image_url',
      'stock',
      'sort_order',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'purchase_invoices',
    columns: [
      'id',
      'branch_id',
      'supplier_id',
      'supplier_name',
      'invoice_number',
      'total_amount',
      'amount_paid',
      'balance_due',
      'due_date',
      'status',
      'note',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'supplier_payments',
    columns: [
      'id',
      'branch_id',
      'supplier_id',
      'purchase_id',
      'amount',
      'payment_method',
      'reference',
      'note',
      'paid_at',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'purchase_orders',
    columns: [
      'id',
      'branch_id',
      'supplier_id',
      'supplier_name',
      'order_number',
      'status',
      'total_amount',
      'expected_on',
      'note',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'purchase_order_items',
    columns: [
      'id',
      'branch_id',
      'purchase_order_id',
      'product_id',
      'product_name',
      'quantity',
      'unit',
      'unit_cost',
      'line_total',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'stock_batches',
    columns: [
      'id',
      'branch_id',
      'product_id',
      'batch_number',
      'quantity_received',
      'quantity_remaining',
      'unit_cost',
      'purchase_id',
      'supplier_id',
      'expiry_date',
      'received_at',
      'finished_at',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'stock_transfers',
    columns: [
      'id',
      'branch_id',
      'from_branch_id',
      'to_branch_id',
      'product_id',
      'product_name',
      'quantity',
      'unit',
      'status',
      'requested_by',
      'approved_by',
      'received_by',
      'note',
      'requested_at',
      'approved_at',
      'received_at',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'customer_invoices',
    columns: [
      'id',
      'branch_id',
      'invoice_number',
      'customer_id',
      'customer_name',
      'customer_phone',
      'customer_email',
      'customer_kra_pin',
      'status',
      'issue_date',
      'due_date',
      'subtotal',
      'tax',
      'discount',
      'total_amount',
      'amount_paid',
      'balance_due',
      'payment_method',
      'payment_reference',
      'note',
      'sale_id',
      'sent_at',
      'paid_at',
      'created_by',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'customer_invoice_items',
    columns: [
      'id',
      'branch_id',
      'invoice_id',
      'line_type',
      'product_id',
      'variant_id',
      'service_id',
      'description',
      'quantity',
      'unit',
      'unit_price',
      'unit_cost',
      'sale_to_stock_factor',
      'stock_unit',
      'track_stock',
      'line_total',
      'sort_order',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'quotations',
    columns: [
      'id',
      'branch_id',
      'quotation_no',
      'customer_id',
      'customer_name',
      'subtotal',
      'discount_total',
      'tax_total',
      'total',
      'expiry_date',
      'notes',
      'status',
      'created_by',
      'converted_sale_id',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'quotation_items',
    columns: [
      'id',
      'branch_id',
      'quotation_id',
      'product_id',
      'variant_id',
      'variant_color_id',
      'variant_color_name',
      'product_name',
      'quantity',
      'unit',
      'unit_price',
      'discount',
      'tax',
      'line_total',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'sales',
    columns: [
      'id',
      'branch_id',
      'total_amount',
      'tax',
      'discount',
      'payment_type',
      'is_cash_drawer',
      'user_id',
      'shift_id',
      'customer_id',
      'customer_name',
      'due_date',
      'amount_paid',
      'amount_tendered',
      'change_given',
      'balance_due',
      'payment_provider',
      'payment_reference',
      'payment_status',
      'payment_metadata_json',
      'etims_status',
      'etims_invoice_number',
      'etims_control_unit_invoice_number',
      'etims_control_unit_serial',
      'etims_verification_url',
      'etims_qr_code',
      'etims_submitted_at',
      'etims_error',
      'etims_response_json',
      'refund_sale_id',
      'refund_for_sale_id',
      'refund_note',
      'refunded_at',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'sale_items',
    columns: [
      'id',
      'quantity',
      'unit_price',
      'unit_cost',
      'unit',
      'sale_id',
      'product_id',
      'variant_id',
      'variant_color_id',
      'variant_color_name',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'cash_movements',
    columns: [
      'id',
      'branch_id',
      'shift_id',
      'user_id',
      'type',
      'amount',
      'reason',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'credit_payments',
    columns: [
      'id',
      'branch_id',
      'payment_group_id',
      'customer_id',
      'sale_id',
      'user_id',
      'amount',
      'note',
      'received_at',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'expenses',
    columns: [
      'id',
      'branch_id',
      'category_id',
      'category_name',
      'title',
      'amount',
      'note',
      'incurred_on',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'services',
    columns: [
      'id',
      'branch_id',
      'name',
      'category',
      'description',
      'base_price',
      'duration_minutes',
      'is_active',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'service_fields',
    columns: [
      'id',
      'service_id',
      'label',
      'field_type',
      'options_json',
      'price_map_json',
      'is_required',
      'sort_order',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'service_orders',
    columns: [
      'id',
      'branch_id',
      'service_id',
      'service_name',
      'customer_id',
      'customer_name',
      'entry_mode',
      'scheduled_at',
      'checked_in_at',
      'status',
      'assigned_staff',
      'assigned_staff_user_id',
      'bay_number',
      'price',
      'note',
      'sale_id',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'service_field_values',
    columns: [
      'id',
      'service_order_id',
      'field_id',
      'field_label',
      'field_type',
      'value_text',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'service_sale_items',
    columns: [
      'id',
      'sale_id',
      'service_order_id',
      'service_id',
      'service_name',
      'quantity',
      'unit_price',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'audit_logs',
    columns: [
      'id',
      'branch_id',
      'user_id',
      'user_name',
      'user_role',
      'action',
      'entity_table',
      'entity_id',
      'before_json',
      'after_json',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'payment_methods',
    columns: [
      'id',
      'name',
      'provider_key',
      'is_cash_drawer',
      'is_credit',
      'is_active',
      'sort_order',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'loyalty_rules',
    columns: [
      'id',
      'branch_id',
      'points_per_currency',
      'currency_divisor',
      'min_redemption_points',
      'points_to_currency_factor',
      'is_active',
      'note',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'loyalty_ledger',
    columns: [
      'id',
      'branch_id',
      'customer_id',
      'sale_id',
      'type',
      'points',
      'balance_after',
      'note',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
  {
    name: 'gift_cards',
    columns: [
      'id',
      'branch_id',
      'code',
      'customer_id',
      'initial_balance',
      'balance',
      'currency',
      'is_active',
      'expires_at',
      'note',
      'created_at',
      'updated_at',
      'deleted_at',
      'sync_status',
    ],
  },
];

const syncTableMap = new Map(syncTables.map((table) => [table.name, table]));

function getTableConfig(tableName) {
  const config = syncTableMap.get(tableName);
  if (!config) {
    throw new Error(`Unsupported sync table: ${tableName}`);
  }
  return config;
}

function sanitizeRecord(tableName, record) {
  const config = getTableConfig(tableName);
  const sanitized = {};

  for (const column of config.columns) {
    if (column === 'sync_status') {
      continue;
    }
    if (Object.prototype.hasOwnProperty.call(record, column)) {
      sanitized[column] = record[column];
    }
  }

  return sanitized;
}

module.exports = {
  syncTables,
  getTableConfig,
  sanitizeRecord,
};
